Update update_m3u.yml

diff --git a/.github/workflows/update_m3u.yml b/.github/workflows/update_m3u.yml
--- a/.github/workflows/update_m3u.yml
+++ b/.github/workflows/update_m3u.yml
@@ -9,13 +9,20 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
+      - name: Set Timezone
+        uses: zcong1993/setup-timezone@v2.0.0
+        with:
+          timezoneLinux: Asia/Dhaka  # Replace with your desired time zone
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version:   
- '3.x'
+          python-version: '3.x'
       - name: Install Dependencies
-        run:   
- pip install requests beautifulsoup4
+        run: pip install requests beautifulsoup4
       - name: Update m3u
-        run: python update_m3u.py
+        run: |
+          python update_m3u.py
+          if [ $? -ne 0 ]; then
+            echo "Error: Python script failed"
+            exit 1
+          fi
